/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the DomainArrayType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainArrayType{}

// DomainArrayType Array of domain values
type DomainArrayType struct {
	Content []DomainType `json:"content,omitempty"`
}

// NewDomainArrayType instantiates a new DomainArrayType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainArrayType() *DomainArrayType {
	this := DomainArrayType{}
	return &this
}

// NewDomainArrayTypeWithDefaults instantiates a new DomainArrayType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainArrayTypeWithDefaults() *DomainArrayType {
	this := DomainArrayType{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *DomainArrayType) GetContent() []DomainType {
	if o == nil || IsNil(o.Content) {
		var ret []DomainType
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainArrayType) GetContentOk() ([]DomainType, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *DomainArrayType) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []DomainType and assigns it to the Content field.
func (o *DomainArrayType) SetContent(v []DomainType) {
	o.Content = v
}

func (o DomainArrayType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainArrayType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

type NullableDomainArrayType struct {
	value *DomainArrayType
	isSet bool
}

func (v NullableDomainArrayType) Get() *DomainArrayType {
	return v.value
}

func (v *NullableDomainArrayType) Set(val *DomainArrayType) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainArrayType) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainArrayType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainArrayType(val *DomainArrayType) *NullableDomainArrayType {
	return &NullableDomainArrayType{value: val, isSet: true}
}

func (v NullableDomainArrayType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainArrayType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


