/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchCompanyDataTypeAssetsAggregateValuesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCompanyDataTypeAssetsAggregateValuesInner{}

// SearchCompanyDataTypeAssetsAggregateValuesInner struct for SearchCompanyDataTypeAssetsAggregateValuesInner
type SearchCompanyDataTypeAssetsAggregateValuesInner struct {
	Code *string `json:"code,omitempty"`
	Value *float32 `json:"value,omitempty"`
}

// NewSearchCompanyDataTypeAssetsAggregateValuesInner instantiates a new SearchCompanyDataTypeAssetsAggregateValuesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCompanyDataTypeAssetsAggregateValuesInner() *SearchCompanyDataTypeAssetsAggregateValuesInner {
	this := SearchCompanyDataTypeAssetsAggregateValuesInner{}
	return &this
}

// NewSearchCompanyDataTypeAssetsAggregateValuesInnerWithDefaults instantiates a new SearchCompanyDataTypeAssetsAggregateValuesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCompanyDataTypeAssetsAggregateValuesInnerWithDefaults() *SearchCompanyDataTypeAssetsAggregateValuesInner {
	this := SearchCompanyDataTypeAssetsAggregateValuesInner{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeAssetsAggregateValuesInner) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeAssetsAggregateValuesInner) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeAssetsAggregateValuesInner) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *SearchCompanyDataTypeAssetsAggregateValuesInner) SetCode(v string) {
	o.Code = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeAssetsAggregateValuesInner) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeAssetsAggregateValuesInner) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeAssetsAggregateValuesInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *SearchCompanyDataTypeAssetsAggregateValuesInner) SetValue(v float32) {
	o.Value = &v
}

func (o SearchCompanyDataTypeAssetsAggregateValuesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCompanyDataTypeAssetsAggregateValuesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableSearchCompanyDataTypeAssetsAggregateValuesInner struct {
	value *SearchCompanyDataTypeAssetsAggregateValuesInner
	isSet bool
}

func (v NullableSearchCompanyDataTypeAssetsAggregateValuesInner) Get() *SearchCompanyDataTypeAssetsAggregateValuesInner {
	return v.value
}

func (v *NullableSearchCompanyDataTypeAssetsAggregateValuesInner) Set(val *SearchCompanyDataTypeAssetsAggregateValuesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCompanyDataTypeAssetsAggregateValuesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCompanyDataTypeAssetsAggregateValuesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCompanyDataTypeAssetsAggregateValuesInner(val *SearchCompanyDataTypeAssetsAggregateValuesInner) *NullableSearchCompanyDataTypeAssetsAggregateValuesInner {
	return &NullableSearchCompanyDataTypeAssetsAggregateValuesInner{value: val, isSet: true}
}

func (v NullableSearchCompanyDataTypeAssetsAggregateValuesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCompanyDataTypeAssetsAggregateValuesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


