/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchCompanyDataTypeIstatTownCode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCompanyDataTypeIstatTownCode{}

// SearchCompanyDataTypeIstatTownCode struct for SearchCompanyDataTypeIstatTownCode
type SearchCompanyDataTypeIstatTownCode struct {
	Code *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewSearchCompanyDataTypeIstatTownCode instantiates a new SearchCompanyDataTypeIstatTownCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCompanyDataTypeIstatTownCode() *SearchCompanyDataTypeIstatTownCode {
	this := SearchCompanyDataTypeIstatTownCode{}
	return &this
}

// NewSearchCompanyDataTypeIstatTownCodeWithDefaults instantiates a new SearchCompanyDataTypeIstatTownCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCompanyDataTypeIstatTownCodeWithDefaults() *SearchCompanyDataTypeIstatTownCode {
	this := SearchCompanyDataTypeIstatTownCode{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeIstatTownCode) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeIstatTownCode) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeIstatTownCode) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *SearchCompanyDataTypeIstatTownCode) SetCode(v string) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeIstatTownCode) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeIstatTownCode) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeIstatTownCode) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SearchCompanyDataTypeIstatTownCode) SetDescription(v string) {
	o.Description = &v
}

func (o SearchCompanyDataTypeIstatTownCode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCompanyDataTypeIstatTownCode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableSearchCompanyDataTypeIstatTownCode struct {
	value *SearchCompanyDataTypeIstatTownCode
	isSet bool
}

func (v NullableSearchCompanyDataTypeIstatTownCode) Get() *SearchCompanyDataTypeIstatTownCode {
	return v.value
}

func (v *NullableSearchCompanyDataTypeIstatTownCode) Set(val *SearchCompanyDataTypeIstatTownCode) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCompanyDataTypeIstatTownCode) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCompanyDataTypeIstatTownCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCompanyDataTypeIstatTownCode(val *SearchCompanyDataTypeIstatTownCode) *NullableSearchCompanyDataTypeIstatTownCode {
	return &NullableSearchCompanyDataTypeIstatTownCode{value: val, isSet: true}
}

func (v NullableSearchCompanyDataTypeIstatTownCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCompanyDataTypeIstatTownCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


