/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchCompanyDataTypeWebAndSocial type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCompanyDataTypeWebAndSocial{}

// SearchCompanyDataTypeWebAndSocial struct for SearchCompanyDataTypeWebAndSocial
type SearchCompanyDataTypeWebAndSocial struct {
	ECommerce *string `json:"eCommerce,omitempty"`
	Website *string `json:"website,omitempty"`
	HasSocial *bool `json:"hasSocial,omitempty"`
	Facebook *string `json:"facebook,omitempty"`
	Youtube *string `json:"youtube,omitempty"`
	Twitter *string `json:"twitter,omitempty"`
	Instagram *string `json:"instagram,omitempty"`
	Linkedin *string `json:"linkedin,omitempty"`
	Pinterest *string `json:"pinterest,omitempty"`
	Vimeo *string `json:"vimeo,omitempty"`
}

// NewSearchCompanyDataTypeWebAndSocial instantiates a new SearchCompanyDataTypeWebAndSocial object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCompanyDataTypeWebAndSocial() *SearchCompanyDataTypeWebAndSocial {
	this := SearchCompanyDataTypeWebAndSocial{}
	return &this
}

// NewSearchCompanyDataTypeWebAndSocialWithDefaults instantiates a new SearchCompanyDataTypeWebAndSocial object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCompanyDataTypeWebAndSocialWithDefaults() *SearchCompanyDataTypeWebAndSocial {
	this := SearchCompanyDataTypeWebAndSocial{}
	return &this
}

// GetECommerce returns the ECommerce field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeWebAndSocial) GetECommerce() string {
	if o == nil || IsNil(o.ECommerce) {
		var ret string
		return ret
	}
	return *o.ECommerce
}

// GetECommerceOk returns a tuple with the ECommerce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeWebAndSocial) GetECommerceOk() (*string, bool) {
	if o == nil || IsNil(o.ECommerce) {
		return nil, false
	}
	return o.ECommerce, true
}

// HasECommerce returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeWebAndSocial) HasECommerce() bool {
	if o != nil && !IsNil(o.ECommerce) {
		return true
	}

	return false
}

// SetECommerce gets a reference to the given string and assigns it to the ECommerce field.
func (o *SearchCompanyDataTypeWebAndSocial) SetECommerce(v string) {
	o.ECommerce = &v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeWebAndSocial) GetWebsite() string {
	if o == nil || IsNil(o.Website) {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeWebAndSocial) GetWebsiteOk() (*string, bool) {
	if o == nil || IsNil(o.Website) {
		return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeWebAndSocial) HasWebsite() bool {
	if o != nil && !IsNil(o.Website) {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *SearchCompanyDataTypeWebAndSocial) SetWebsite(v string) {
	o.Website = &v
}

// GetHasSocial returns the HasSocial field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeWebAndSocial) GetHasSocial() bool {
	if o == nil || IsNil(o.HasSocial) {
		var ret bool
		return ret
	}
	return *o.HasSocial
}

// GetHasSocialOk returns a tuple with the HasSocial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeWebAndSocial) GetHasSocialOk() (*bool, bool) {
	if o == nil || IsNil(o.HasSocial) {
		return nil, false
	}
	return o.HasSocial, true
}

// HasHasSocial returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeWebAndSocial) HasHasSocial() bool {
	if o != nil && !IsNil(o.HasSocial) {
		return true
	}

	return false
}

// SetHasSocial gets a reference to the given bool and assigns it to the HasSocial field.
func (o *SearchCompanyDataTypeWebAndSocial) SetHasSocial(v bool) {
	o.HasSocial = &v
}

// GetFacebook returns the Facebook field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeWebAndSocial) GetFacebook() string {
	if o == nil || IsNil(o.Facebook) {
		var ret string
		return ret
	}
	return *o.Facebook
}

// GetFacebookOk returns a tuple with the Facebook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeWebAndSocial) GetFacebookOk() (*string, bool) {
	if o == nil || IsNil(o.Facebook) {
		return nil, false
	}
	return o.Facebook, true
}

// HasFacebook returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeWebAndSocial) HasFacebook() bool {
	if o != nil && !IsNil(o.Facebook) {
		return true
	}

	return false
}

// SetFacebook gets a reference to the given string and assigns it to the Facebook field.
func (o *SearchCompanyDataTypeWebAndSocial) SetFacebook(v string) {
	o.Facebook = &v
}

// GetYoutube returns the Youtube field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeWebAndSocial) GetYoutube() string {
	if o == nil || IsNil(o.Youtube) {
		var ret string
		return ret
	}
	return *o.Youtube
}

// GetYoutubeOk returns a tuple with the Youtube field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeWebAndSocial) GetYoutubeOk() (*string, bool) {
	if o == nil || IsNil(o.Youtube) {
		return nil, false
	}
	return o.Youtube, true
}

// HasYoutube returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeWebAndSocial) HasYoutube() bool {
	if o != nil && !IsNil(o.Youtube) {
		return true
	}

	return false
}

// SetYoutube gets a reference to the given string and assigns it to the Youtube field.
func (o *SearchCompanyDataTypeWebAndSocial) SetYoutube(v string) {
	o.Youtube = &v
}

// GetTwitter returns the Twitter field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeWebAndSocial) GetTwitter() string {
	if o == nil || IsNil(o.Twitter) {
		var ret string
		return ret
	}
	return *o.Twitter
}

// GetTwitterOk returns a tuple with the Twitter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeWebAndSocial) GetTwitterOk() (*string, bool) {
	if o == nil || IsNil(o.Twitter) {
		return nil, false
	}
	return o.Twitter, true
}

// HasTwitter returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeWebAndSocial) HasTwitter() bool {
	if o != nil && !IsNil(o.Twitter) {
		return true
	}

	return false
}

// SetTwitter gets a reference to the given string and assigns it to the Twitter field.
func (o *SearchCompanyDataTypeWebAndSocial) SetTwitter(v string) {
	o.Twitter = &v
}

// GetInstagram returns the Instagram field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeWebAndSocial) GetInstagram() string {
	if o == nil || IsNil(o.Instagram) {
		var ret string
		return ret
	}
	return *o.Instagram
}

// GetInstagramOk returns a tuple with the Instagram field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeWebAndSocial) GetInstagramOk() (*string, bool) {
	if o == nil || IsNil(o.Instagram) {
		return nil, false
	}
	return o.Instagram, true
}

// HasInstagram returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeWebAndSocial) HasInstagram() bool {
	if o != nil && !IsNil(o.Instagram) {
		return true
	}

	return false
}

// SetInstagram gets a reference to the given string and assigns it to the Instagram field.
func (o *SearchCompanyDataTypeWebAndSocial) SetInstagram(v string) {
	o.Instagram = &v
}

// GetLinkedin returns the Linkedin field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeWebAndSocial) GetLinkedin() string {
	if o == nil || IsNil(o.Linkedin) {
		var ret string
		return ret
	}
	return *o.Linkedin
}

// GetLinkedinOk returns a tuple with the Linkedin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeWebAndSocial) GetLinkedinOk() (*string, bool) {
	if o == nil || IsNil(o.Linkedin) {
		return nil, false
	}
	return o.Linkedin, true
}

// HasLinkedin returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeWebAndSocial) HasLinkedin() bool {
	if o != nil && !IsNil(o.Linkedin) {
		return true
	}

	return false
}

// SetLinkedin gets a reference to the given string and assigns it to the Linkedin field.
func (o *SearchCompanyDataTypeWebAndSocial) SetLinkedin(v string) {
	o.Linkedin = &v
}

// GetPinterest returns the Pinterest field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeWebAndSocial) GetPinterest() string {
	if o == nil || IsNil(o.Pinterest) {
		var ret string
		return ret
	}
	return *o.Pinterest
}

// GetPinterestOk returns a tuple with the Pinterest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeWebAndSocial) GetPinterestOk() (*string, bool) {
	if o == nil || IsNil(o.Pinterest) {
		return nil, false
	}
	return o.Pinterest, true
}

// HasPinterest returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeWebAndSocial) HasPinterest() bool {
	if o != nil && !IsNil(o.Pinterest) {
		return true
	}

	return false
}

// SetPinterest gets a reference to the given string and assigns it to the Pinterest field.
func (o *SearchCompanyDataTypeWebAndSocial) SetPinterest(v string) {
	o.Pinterest = &v
}

// GetVimeo returns the Vimeo field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeWebAndSocial) GetVimeo() string {
	if o == nil || IsNil(o.Vimeo) {
		var ret string
		return ret
	}
	return *o.Vimeo
}

// GetVimeoOk returns a tuple with the Vimeo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeWebAndSocial) GetVimeoOk() (*string, bool) {
	if o == nil || IsNil(o.Vimeo) {
		return nil, false
	}
	return o.Vimeo, true
}

// HasVimeo returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeWebAndSocial) HasVimeo() bool {
	if o != nil && !IsNil(o.Vimeo) {
		return true
	}

	return false
}

// SetVimeo gets a reference to the given string and assigns it to the Vimeo field.
func (o *SearchCompanyDataTypeWebAndSocial) SetVimeo(v string) {
	o.Vimeo = &v
}

func (o SearchCompanyDataTypeWebAndSocial) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCompanyDataTypeWebAndSocial) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ECommerce) {
		toSerialize["eCommerce"] = o.ECommerce
	}
	if !IsNil(o.Website) {
		toSerialize["website"] = o.Website
	}
	if !IsNil(o.HasSocial) {
		toSerialize["hasSocial"] = o.HasSocial
	}
	if !IsNil(o.Facebook) {
		toSerialize["facebook"] = o.Facebook
	}
	if !IsNil(o.Youtube) {
		toSerialize["youtube"] = o.Youtube
	}
	if !IsNil(o.Twitter) {
		toSerialize["twitter"] = o.Twitter
	}
	if !IsNil(o.Instagram) {
		toSerialize["instagram"] = o.Instagram
	}
	if !IsNil(o.Linkedin) {
		toSerialize["linkedin"] = o.Linkedin
	}
	if !IsNil(o.Pinterest) {
		toSerialize["pinterest"] = o.Pinterest
	}
	if !IsNil(o.Vimeo) {
		toSerialize["vimeo"] = o.Vimeo
	}
	return toSerialize, nil
}

type NullableSearchCompanyDataTypeWebAndSocial struct {
	value *SearchCompanyDataTypeWebAndSocial
	isSet bool
}

func (v NullableSearchCompanyDataTypeWebAndSocial) Get() *SearchCompanyDataTypeWebAndSocial {
	return v.value
}

func (v *NullableSearchCompanyDataTypeWebAndSocial) Set(val *SearchCompanyDataTypeWebAndSocial) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCompanyDataTypeWebAndSocial) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCompanyDataTypeWebAndSocial) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCompanyDataTypeWebAndSocial(val *SearchCompanyDataTypeWebAndSocial) *NullableSearchCompanyDataTypeWebAndSocial {
	return &NullableSearchCompanyDataTypeWebAndSocial{value: val, isSet: true}
}

func (v NullableSearchCompanyDataTypeWebAndSocial) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCompanyDataTypeWebAndSocial) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


