/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchDataArrayType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchDataArrayType{}

// SearchDataArrayType Search Data array
type SearchDataArrayType struct {
	Content []SearchCompanyDataType `json:"content,omitempty"`
}

// NewSearchDataArrayType instantiates a new SearchDataArrayType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchDataArrayType() *SearchDataArrayType {
	this := SearchDataArrayType{}
	return &this
}

// NewSearchDataArrayTypeWithDefaults instantiates a new SearchDataArrayType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchDataArrayTypeWithDefaults() *SearchDataArrayType {
	this := SearchDataArrayType{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *SearchDataArrayType) GetContent() []SearchCompanyDataType {
	if o == nil || IsNil(o.Content) {
		var ret []SearchCompanyDataType
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchDataArrayType) GetContentOk() ([]SearchCompanyDataType, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *SearchDataArrayType) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []SearchCompanyDataType and assigns it to the Content field.
func (o *SearchDataArrayType) SetContent(v []SearchCompanyDataType) {
	o.Content = v
}

func (o SearchDataArrayType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchDataArrayType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

type NullableSearchDataArrayType struct {
	value *SearchDataArrayType
	isSet bool
}

func (v NullableSearchDataArrayType) Get() *SearchDataArrayType {
	return v.value
}

func (v *NullableSearchDataArrayType) Set(val *SearchDataArrayType) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchDataArrayType) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchDataArrayType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchDataArrayType(val *SearchDataArrayType) *NullableSearchDataArrayType {
	return &NullableSearchDataArrayType{value: val, isSet: true}
}

func (v NullableSearchDataArrayType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchDataArrayType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


