/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchCompanyDataTypeAffiliateCompaniesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCompanyDataTypeAffiliateCompaniesInner{}

// SearchCompanyDataTypeAffiliateCompaniesInner struct for SearchCompanyDataTypeAffiliateCompaniesInner
type SearchCompanyDataTypeAffiliateCompaniesInner struct {
	TaxCode *string `json:"taxCode,omitempty"`
	CompanyName *string `json:"companyName,omitempty"`
	PercentShare *float32 `json:"percentShare,omitempty"`
}

// NewSearchCompanyDataTypeAffiliateCompaniesInner instantiates a new SearchCompanyDataTypeAffiliateCompaniesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCompanyDataTypeAffiliateCompaniesInner() *SearchCompanyDataTypeAffiliateCompaniesInner {
	this := SearchCompanyDataTypeAffiliateCompaniesInner{}
	return &this
}

// NewSearchCompanyDataTypeAffiliateCompaniesInnerWithDefaults instantiates a new SearchCompanyDataTypeAffiliateCompaniesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCompanyDataTypeAffiliateCompaniesInnerWithDefaults() *SearchCompanyDataTypeAffiliateCompaniesInner {
	this := SearchCompanyDataTypeAffiliateCompaniesInner{}
	return &this
}

// GetTaxCode returns the TaxCode field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) GetTaxCode() string {
	if o == nil || IsNil(o.TaxCode) {
		var ret string
		return ret
	}
	return *o.TaxCode
}

// GetTaxCodeOk returns a tuple with the TaxCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) GetTaxCodeOk() (*string, bool) {
	if o == nil || IsNil(o.TaxCode) {
		return nil, false
	}
	return o.TaxCode, true
}

// HasTaxCode returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) HasTaxCode() bool {
	if o != nil && !IsNil(o.TaxCode) {
		return true
	}

	return false
}

// SetTaxCode gets a reference to the given string and assigns it to the TaxCode field.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) SetTaxCode(v string) {
	o.TaxCode = &v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetPercentShare returns the PercentShare field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) GetPercentShare() float32 {
	if o == nil || IsNil(o.PercentShare) {
		var ret float32
		return ret
	}
	return *o.PercentShare
}

// GetPercentShareOk returns a tuple with the PercentShare field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) GetPercentShareOk() (*float32, bool) {
	if o == nil || IsNil(o.PercentShare) {
		return nil, false
	}
	return o.PercentShare, true
}

// HasPercentShare returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) HasPercentShare() bool {
	if o != nil && !IsNil(o.PercentShare) {
		return true
	}

	return false
}

// SetPercentShare gets a reference to the given float32 and assigns it to the PercentShare field.
func (o *SearchCompanyDataTypeAffiliateCompaniesInner) SetPercentShare(v float32) {
	o.PercentShare = &v
}

func (o SearchCompanyDataTypeAffiliateCompaniesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCompanyDataTypeAffiliateCompaniesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TaxCode) {
		toSerialize["taxCode"] = o.TaxCode
	}
	if !IsNil(o.CompanyName) {
		toSerialize["companyName"] = o.CompanyName
	}
	if !IsNil(o.PercentShare) {
		toSerialize["percentShare"] = o.PercentShare
	}
	return toSerialize, nil
}

type NullableSearchCompanyDataTypeAffiliateCompaniesInner struct {
	value *SearchCompanyDataTypeAffiliateCompaniesInner
	isSet bool
}

func (v NullableSearchCompanyDataTypeAffiliateCompaniesInner) Get() *SearchCompanyDataTypeAffiliateCompaniesInner {
	return v.value
}

func (v *NullableSearchCompanyDataTypeAffiliateCompaniesInner) Set(val *SearchCompanyDataTypeAffiliateCompaniesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCompanyDataTypeAffiliateCompaniesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCompanyDataTypeAffiliateCompaniesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCompanyDataTypeAffiliateCompaniesInner(val *SearchCompanyDataTypeAffiliateCompaniesInner) *NullableSearchCompanyDataTypeAffiliateCompaniesInner {
	return &NullableSearchCompanyDataTypeAffiliateCompaniesInner{value: val, isSet: true}
}

func (v NullableSearchCompanyDataTypeAffiliateCompaniesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCompanyDataTypeAffiliateCompaniesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


