/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchCompanyDataTypeMail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCompanyDataTypeMail{}

// SearchCompanyDataTypeMail struct for SearchCompanyDataTypeMail
type SearchCompanyDataTypeMail struct {
	Email *string `json:"email,omitempty"`
}

// NewSearchCompanyDataTypeMail instantiates a new SearchCompanyDataTypeMail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCompanyDataTypeMail() *SearchCompanyDataTypeMail {
	this := SearchCompanyDataTypeMail{}
	return &this
}

// NewSearchCompanyDataTypeMailWithDefaults instantiates a new SearchCompanyDataTypeMail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCompanyDataTypeMailWithDefaults() *SearchCompanyDataTypeMail {
	this := SearchCompanyDataTypeMail{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeMail) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeMail) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeMail) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *SearchCompanyDataTypeMail) SetEmail(v string) {
	o.Email = &v
}

func (o SearchCompanyDataTypeMail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCompanyDataTypeMail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

type NullableSearchCompanyDataTypeMail struct {
	value *SearchCompanyDataTypeMail
	isSet bool
}

func (v NullableSearchCompanyDataTypeMail) Get() *SearchCompanyDataTypeMail {
	return v.value
}

func (v *NullableSearchCompanyDataTypeMail) Set(val *SearchCompanyDataTypeMail) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCompanyDataTypeMail) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCompanyDataTypeMail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCompanyDataTypeMail(val *SearchCompanyDataTypeMail) *NullableSearchCompanyDataTypeMail {
	return &NullableSearchCompanyDataTypeMail{value: val, isSet: true}
}

func (v NullableSearchCompanyDataTypeMail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCompanyDataTypeMail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


