/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the FiltersTypeNumericfiltersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FiltersTypeNumericfiltersInner{}

// FiltersTypeNumericfiltersInner struct for FiltersTypeNumericfiltersInner
type FiltersTypeNumericfiltersInner struct {
	FilterId *string `json:"filterId,omitempty"`
	Value *NumericFilterType `json:"value,omitempty"`
}

// NewFiltersTypeNumericfiltersInner instantiates a new FiltersTypeNumericfiltersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFiltersTypeNumericfiltersInner() *FiltersTypeNumericfiltersInner {
	this := FiltersTypeNumericfiltersInner{}
	return &this
}

// NewFiltersTypeNumericfiltersInnerWithDefaults instantiates a new FiltersTypeNumericfiltersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFiltersTypeNumericfiltersInnerWithDefaults() *FiltersTypeNumericfiltersInner {
	this := FiltersTypeNumericfiltersInner{}
	return &this
}

// GetFilterId returns the FilterId field value if set, zero value otherwise.
func (o *FiltersTypeNumericfiltersInner) GetFilterId() string {
	if o == nil || IsNil(o.FilterId) {
		var ret string
		return ret
	}
	return *o.FilterId
}

// GetFilterIdOk returns a tuple with the FilterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersTypeNumericfiltersInner) GetFilterIdOk() (*string, bool) {
	if o == nil || IsNil(o.FilterId) {
		return nil, false
	}
	return o.FilterId, true
}

// HasFilterId returns a boolean if a field has been set.
func (o *FiltersTypeNumericfiltersInner) HasFilterId() bool {
	if o != nil && !IsNil(o.FilterId) {
		return true
	}

	return false
}

// SetFilterId gets a reference to the given string and assigns it to the FilterId field.
func (o *FiltersTypeNumericfiltersInner) SetFilterId(v string) {
	o.FilterId = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *FiltersTypeNumericfiltersInner) GetValue() NumericFilterType {
	if o == nil || IsNil(o.Value) {
		var ret NumericFilterType
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersTypeNumericfiltersInner) GetValueOk() (*NumericFilterType, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *FiltersTypeNumericfiltersInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given NumericFilterType and assigns it to the Value field.
func (o *FiltersTypeNumericfiltersInner) SetValue(v NumericFilterType) {
	o.Value = &v
}

func (o FiltersTypeNumericfiltersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FiltersTypeNumericfiltersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FilterId) {
		toSerialize["filterId"] = o.FilterId
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableFiltersTypeNumericfiltersInner struct {
	value *FiltersTypeNumericfiltersInner
	isSet bool
}

func (v NullableFiltersTypeNumericfiltersInner) Get() *FiltersTypeNumericfiltersInner {
	return v.value
}

func (v *NullableFiltersTypeNumericfiltersInner) Set(val *FiltersTypeNumericfiltersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFiltersTypeNumericfiltersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFiltersTypeNumericfiltersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFiltersTypeNumericfiltersInner(val *FiltersTypeNumericfiltersInner) *NullableFiltersTypeNumericfiltersInner {
	return &NullableFiltersTypeNumericfiltersInner{value: val, isSet: true}
}

func (v NullableFiltersTypeNumericfiltersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFiltersTypeNumericfiltersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


