/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the DownloadCompanyDataTypePortfolioInformationProduct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DownloadCompanyDataTypePortfolioInformationProduct{}

// DownloadCompanyDataTypePortfolioInformationProduct struct for DownloadCompanyDataTypePortfolioInformationProduct
type DownloadCompanyDataTypePortfolioInformationProduct struct {
	Id *string `json:"id,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewDownloadCompanyDataTypePortfolioInformationProduct instantiates a new DownloadCompanyDataTypePortfolioInformationProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDownloadCompanyDataTypePortfolioInformationProduct() *DownloadCompanyDataTypePortfolioInformationProduct {
	this := DownloadCompanyDataTypePortfolioInformationProduct{}
	return &this
}

// NewDownloadCompanyDataTypePortfolioInformationProductWithDefaults instantiates a new DownloadCompanyDataTypePortfolioInformationProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDownloadCompanyDataTypePortfolioInformationProductWithDefaults() *DownloadCompanyDataTypePortfolioInformationProduct {
	this := DownloadCompanyDataTypePortfolioInformationProduct{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DownloadCompanyDataTypePortfolioInformationProduct) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadCompanyDataTypePortfolioInformationProduct) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DownloadCompanyDataTypePortfolioInformationProduct) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DownloadCompanyDataTypePortfolioInformationProduct) SetId(v string) {
	o.Id = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DownloadCompanyDataTypePortfolioInformationProduct) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadCompanyDataTypePortfolioInformationProduct) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DownloadCompanyDataTypePortfolioInformationProduct) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DownloadCompanyDataTypePortfolioInformationProduct) SetDescription(v string) {
	o.Description = &v
}

func (o DownloadCompanyDataTypePortfolioInformationProduct) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DownloadCompanyDataTypePortfolioInformationProduct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableDownloadCompanyDataTypePortfolioInformationProduct struct {
	value *DownloadCompanyDataTypePortfolioInformationProduct
	isSet bool
}

func (v NullableDownloadCompanyDataTypePortfolioInformationProduct) Get() *DownloadCompanyDataTypePortfolioInformationProduct {
	return v.value
}

func (v *NullableDownloadCompanyDataTypePortfolioInformationProduct) Set(val *DownloadCompanyDataTypePortfolioInformationProduct) {
	v.value = val
	v.isSet = true
}

func (v NullableDownloadCompanyDataTypePortfolioInformationProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableDownloadCompanyDataTypePortfolioInformationProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDownloadCompanyDataTypePortfolioInformationProduct(val *DownloadCompanyDataTypePortfolioInformationProduct) *NullableDownloadCompanyDataTypePortfolioInformationProduct {
	return &NullableDownloadCompanyDataTypePortfolioInformationProduct{value: val, isSet: true}
}

func (v NullableDownloadCompanyDataTypePortfolioInformationProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDownloadCompanyDataTypePortfolioInformationProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


