/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchCompanyDataTypeArtisanBusinessRegistry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCompanyDataTypeArtisanBusinessRegistry{}

// SearchCompanyDataTypeArtisanBusinessRegistry struct for SearchCompanyDataTypeArtisanBusinessRegistry
type SearchCompanyDataTypeArtisanBusinessRegistry struct {
	BelongsToArtisanBusinessRegistry *bool `json:"belongsToArtisanBusinessRegistry,omitempty"`
	ArtisanBusinessRegistry *SearchCompanyDataTypeArtisanBusinessRegistryArtisanBusinessRegistry `json:"artisanBusinessRegistry,omitempty"`
}

// NewSearchCompanyDataTypeArtisanBusinessRegistry instantiates a new SearchCompanyDataTypeArtisanBusinessRegistry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCompanyDataTypeArtisanBusinessRegistry() *SearchCompanyDataTypeArtisanBusinessRegistry {
	this := SearchCompanyDataTypeArtisanBusinessRegistry{}
	return &this
}

// NewSearchCompanyDataTypeArtisanBusinessRegistryWithDefaults instantiates a new SearchCompanyDataTypeArtisanBusinessRegistry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCompanyDataTypeArtisanBusinessRegistryWithDefaults() *SearchCompanyDataTypeArtisanBusinessRegistry {
	this := SearchCompanyDataTypeArtisanBusinessRegistry{}
	return &this
}

// GetBelongsToArtisanBusinessRegistry returns the BelongsToArtisanBusinessRegistry field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeArtisanBusinessRegistry) GetBelongsToArtisanBusinessRegistry() bool {
	if o == nil || IsNil(o.BelongsToArtisanBusinessRegistry) {
		var ret bool
		return ret
	}
	return *o.BelongsToArtisanBusinessRegistry
}

// GetBelongsToArtisanBusinessRegistryOk returns a tuple with the BelongsToArtisanBusinessRegistry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeArtisanBusinessRegistry) GetBelongsToArtisanBusinessRegistryOk() (*bool, bool) {
	if o == nil || IsNil(o.BelongsToArtisanBusinessRegistry) {
		return nil, false
	}
	return o.BelongsToArtisanBusinessRegistry, true
}

// HasBelongsToArtisanBusinessRegistry returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeArtisanBusinessRegistry) HasBelongsToArtisanBusinessRegistry() bool {
	if o != nil && !IsNil(o.BelongsToArtisanBusinessRegistry) {
		return true
	}

	return false
}

// SetBelongsToArtisanBusinessRegistry gets a reference to the given bool and assigns it to the BelongsToArtisanBusinessRegistry field.
func (o *SearchCompanyDataTypeArtisanBusinessRegistry) SetBelongsToArtisanBusinessRegistry(v bool) {
	o.BelongsToArtisanBusinessRegistry = &v
}

// GetArtisanBusinessRegistry returns the ArtisanBusinessRegistry field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeArtisanBusinessRegistry) GetArtisanBusinessRegistry() SearchCompanyDataTypeArtisanBusinessRegistryArtisanBusinessRegistry {
	if o == nil || IsNil(o.ArtisanBusinessRegistry) {
		var ret SearchCompanyDataTypeArtisanBusinessRegistryArtisanBusinessRegistry
		return ret
	}
	return *o.ArtisanBusinessRegistry
}

// GetArtisanBusinessRegistryOk returns a tuple with the ArtisanBusinessRegistry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeArtisanBusinessRegistry) GetArtisanBusinessRegistryOk() (*SearchCompanyDataTypeArtisanBusinessRegistryArtisanBusinessRegistry, bool) {
	if o == nil || IsNil(o.ArtisanBusinessRegistry) {
		return nil, false
	}
	return o.ArtisanBusinessRegistry, true
}

// HasArtisanBusinessRegistry returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeArtisanBusinessRegistry) HasArtisanBusinessRegistry() bool {
	if o != nil && !IsNil(o.ArtisanBusinessRegistry) {
		return true
	}

	return false
}

// SetArtisanBusinessRegistry gets a reference to the given SearchCompanyDataTypeArtisanBusinessRegistryArtisanBusinessRegistry and assigns it to the ArtisanBusinessRegistry field.
func (o *SearchCompanyDataTypeArtisanBusinessRegistry) SetArtisanBusinessRegistry(v SearchCompanyDataTypeArtisanBusinessRegistryArtisanBusinessRegistry) {
	o.ArtisanBusinessRegistry = &v
}

func (o SearchCompanyDataTypeArtisanBusinessRegistry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCompanyDataTypeArtisanBusinessRegistry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BelongsToArtisanBusinessRegistry) {
		toSerialize["belongsToArtisanBusinessRegistry"] = o.BelongsToArtisanBusinessRegistry
	}
	if !IsNil(o.ArtisanBusinessRegistry) {
		toSerialize["artisanBusinessRegistry"] = o.ArtisanBusinessRegistry
	}
	return toSerialize, nil
}

type NullableSearchCompanyDataTypeArtisanBusinessRegistry struct {
	value *SearchCompanyDataTypeArtisanBusinessRegistry
	isSet bool
}

func (v NullableSearchCompanyDataTypeArtisanBusinessRegistry) Get() *SearchCompanyDataTypeArtisanBusinessRegistry {
	return v.value
}

func (v *NullableSearchCompanyDataTypeArtisanBusinessRegistry) Set(val *SearchCompanyDataTypeArtisanBusinessRegistry) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCompanyDataTypeArtisanBusinessRegistry) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCompanyDataTypeArtisanBusinessRegistry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCompanyDataTypeArtisanBusinessRegistry(val *SearchCompanyDataTypeArtisanBusinessRegistry) *NullableSearchCompanyDataTypeArtisanBusinessRegistry {
	return &NullableSearchCompanyDataTypeArtisanBusinessRegistry{value: val, isSet: true}
}

func (v NullableSearchCompanyDataTypeArtisanBusinessRegistry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCompanyDataTypeArtisanBusinessRegistry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


