/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchCompanyDataTypeStateOwnedTelco type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCompanyDataTypeStateOwnedTelco{}

// SearchCompanyDataTypeStateOwnedTelco struct for SearchCompanyDataTypeStateOwnedTelco
type SearchCompanyDataTypeStateOwnedTelco struct {
	LandLine *float32 `json:"landLine,omitempty"`
	LandLineTrend *float32 `json:"landLineTrend,omitempty"`
	Mobile *float32 `json:"mobile,omitempty"`
	MobileTrend *float32 `json:"mobileTrend,omitempty"`
}

// NewSearchCompanyDataTypeStateOwnedTelco instantiates a new SearchCompanyDataTypeStateOwnedTelco object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCompanyDataTypeStateOwnedTelco() *SearchCompanyDataTypeStateOwnedTelco {
	this := SearchCompanyDataTypeStateOwnedTelco{}
	return &this
}

// NewSearchCompanyDataTypeStateOwnedTelcoWithDefaults instantiates a new SearchCompanyDataTypeStateOwnedTelco object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCompanyDataTypeStateOwnedTelcoWithDefaults() *SearchCompanyDataTypeStateOwnedTelco {
	this := SearchCompanyDataTypeStateOwnedTelco{}
	return &this
}

// GetLandLine returns the LandLine field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeStateOwnedTelco) GetLandLine() float32 {
	if o == nil || IsNil(o.LandLine) {
		var ret float32
		return ret
	}
	return *o.LandLine
}

// GetLandLineOk returns a tuple with the LandLine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeStateOwnedTelco) GetLandLineOk() (*float32, bool) {
	if o == nil || IsNil(o.LandLine) {
		return nil, false
	}
	return o.LandLine, true
}

// HasLandLine returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeStateOwnedTelco) HasLandLine() bool {
	if o != nil && !IsNil(o.LandLine) {
		return true
	}

	return false
}

// SetLandLine gets a reference to the given float32 and assigns it to the LandLine field.
func (o *SearchCompanyDataTypeStateOwnedTelco) SetLandLine(v float32) {
	o.LandLine = &v
}

// GetLandLineTrend returns the LandLineTrend field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeStateOwnedTelco) GetLandLineTrend() float32 {
	if o == nil || IsNil(o.LandLineTrend) {
		var ret float32
		return ret
	}
	return *o.LandLineTrend
}

// GetLandLineTrendOk returns a tuple with the LandLineTrend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeStateOwnedTelco) GetLandLineTrendOk() (*float32, bool) {
	if o == nil || IsNil(o.LandLineTrend) {
		return nil, false
	}
	return o.LandLineTrend, true
}

// HasLandLineTrend returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeStateOwnedTelco) HasLandLineTrend() bool {
	if o != nil && !IsNil(o.LandLineTrend) {
		return true
	}

	return false
}

// SetLandLineTrend gets a reference to the given float32 and assigns it to the LandLineTrend field.
func (o *SearchCompanyDataTypeStateOwnedTelco) SetLandLineTrend(v float32) {
	o.LandLineTrend = &v
}

// GetMobile returns the Mobile field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeStateOwnedTelco) GetMobile() float32 {
	if o == nil || IsNil(o.Mobile) {
		var ret float32
		return ret
	}
	return *o.Mobile
}

// GetMobileOk returns a tuple with the Mobile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeStateOwnedTelco) GetMobileOk() (*float32, bool) {
	if o == nil || IsNil(o.Mobile) {
		return nil, false
	}
	return o.Mobile, true
}

// HasMobile returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeStateOwnedTelco) HasMobile() bool {
	if o != nil && !IsNil(o.Mobile) {
		return true
	}

	return false
}

// SetMobile gets a reference to the given float32 and assigns it to the Mobile field.
func (o *SearchCompanyDataTypeStateOwnedTelco) SetMobile(v float32) {
	o.Mobile = &v
}

// GetMobileTrend returns the MobileTrend field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeStateOwnedTelco) GetMobileTrend() float32 {
	if o == nil || IsNil(o.MobileTrend) {
		var ret float32
		return ret
	}
	return *o.MobileTrend
}

// GetMobileTrendOk returns a tuple with the MobileTrend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeStateOwnedTelco) GetMobileTrendOk() (*float32, bool) {
	if o == nil || IsNil(o.MobileTrend) {
		return nil, false
	}
	return o.MobileTrend, true
}

// HasMobileTrend returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeStateOwnedTelco) HasMobileTrend() bool {
	if o != nil && !IsNil(o.MobileTrend) {
		return true
	}

	return false
}

// SetMobileTrend gets a reference to the given float32 and assigns it to the MobileTrend field.
func (o *SearchCompanyDataTypeStateOwnedTelco) SetMobileTrend(v float32) {
	o.MobileTrend = &v
}

func (o SearchCompanyDataTypeStateOwnedTelco) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCompanyDataTypeStateOwnedTelco) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LandLine) {
		toSerialize["landLine"] = o.LandLine
	}
	if !IsNil(o.LandLineTrend) {
		toSerialize["landLineTrend"] = o.LandLineTrend
	}
	if !IsNil(o.Mobile) {
		toSerialize["mobile"] = o.Mobile
	}
	if !IsNil(o.MobileTrend) {
		toSerialize["mobileTrend"] = o.MobileTrend
	}
	return toSerialize, nil
}

type NullableSearchCompanyDataTypeStateOwnedTelco struct {
	value *SearchCompanyDataTypeStateOwnedTelco
	isSet bool
}

func (v NullableSearchCompanyDataTypeStateOwnedTelco) Get() *SearchCompanyDataTypeStateOwnedTelco {
	return v.value
}

func (v *NullableSearchCompanyDataTypeStateOwnedTelco) Set(val *SearchCompanyDataTypeStateOwnedTelco) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCompanyDataTypeStateOwnedTelco) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCompanyDataTypeStateOwnedTelco) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCompanyDataTypeStateOwnedTelco(val *SearchCompanyDataTypeStateOwnedTelco) *NullableSearchCompanyDataTypeStateOwnedTelco {
	return &NullableSearchCompanyDataTypeStateOwnedTelco{value: val, isSet: true}
}

func (v NullableSearchCompanyDataTypeStateOwnedTelco) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCompanyDataTypeStateOwnedTelco) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


