/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the FiltersTypeStringfiltersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FiltersTypeStringfiltersInner{}

// FiltersTypeStringfiltersInner struct for FiltersTypeStringfiltersInner
type FiltersTypeStringfiltersInner struct {
	FilterId *string `json:"filterId,omitempty"`
	Values []string `json:"values,omitempty"`
}

// NewFiltersTypeStringfiltersInner instantiates a new FiltersTypeStringfiltersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFiltersTypeStringfiltersInner() *FiltersTypeStringfiltersInner {
	this := FiltersTypeStringfiltersInner{}
	return &this
}

// NewFiltersTypeStringfiltersInnerWithDefaults instantiates a new FiltersTypeStringfiltersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFiltersTypeStringfiltersInnerWithDefaults() *FiltersTypeStringfiltersInner {
	this := FiltersTypeStringfiltersInner{}
	return &this
}

// GetFilterId returns the FilterId field value if set, zero value otherwise.
func (o *FiltersTypeStringfiltersInner) GetFilterId() string {
	if o == nil || IsNil(o.FilterId) {
		var ret string
		return ret
	}
	return *o.FilterId
}

// GetFilterIdOk returns a tuple with the FilterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersTypeStringfiltersInner) GetFilterIdOk() (*string, bool) {
	if o == nil || IsNil(o.FilterId) {
		return nil, false
	}
	return o.FilterId, true
}

// HasFilterId returns a boolean if a field has been set.
func (o *FiltersTypeStringfiltersInner) HasFilterId() bool {
	if o != nil && !IsNil(o.FilterId) {
		return true
	}

	return false
}

// SetFilterId gets a reference to the given string and assigns it to the FilterId field.
func (o *FiltersTypeStringfiltersInner) SetFilterId(v string) {
	o.FilterId = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *FiltersTypeStringfiltersInner) GetValues() []string {
	if o == nil || IsNil(o.Values) {
		var ret []string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersTypeStringfiltersInner) GetValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *FiltersTypeStringfiltersInner) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *FiltersTypeStringfiltersInner) SetValues(v []string) {
	o.Values = v
}

func (o FiltersTypeStringfiltersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FiltersTypeStringfiltersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FilterId) {
		toSerialize["filterId"] = o.FilterId
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

type NullableFiltersTypeStringfiltersInner struct {
	value *FiltersTypeStringfiltersInner
	isSet bool
}

func (v NullableFiltersTypeStringfiltersInner) Get() *FiltersTypeStringfiltersInner {
	return v.value
}

func (v *NullableFiltersTypeStringfiltersInner) Set(val *FiltersTypeStringfiltersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFiltersTypeStringfiltersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFiltersTypeStringfiltersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFiltersTypeStringfiltersInner(val *FiltersTypeStringfiltersInner) *NullableFiltersTypeStringfiltersInner {
	return &NullableFiltersTypeStringfiltersInner{value: val, isSet: true}
}

func (v NullableFiltersTypeStringfiltersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFiltersTypeStringfiltersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


