/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchCompanyDataTypeFinancialStability type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCompanyDataTypeFinancialStability{}

// SearchCompanyDataTypeFinancialStability struct for SearchCompanyDataTypeFinancialStability
type SearchCompanyDataTypeFinancialStability struct {
	SecondaryMarginStructure *float32 `json:"secondaryMarginStructure,omitempty"`
	MarginStructure *float32 `json:"marginStructure,omitempty"`
	FixedAssetsCoverageRate *float32 `json:"fixedAssetsCoverageRate,omitempty"`
	MarginStructureIndex *float32 `json:"marginStructureIndex,omitempty"`
	WorkingCapitalCoverage *float32 `json:"workingCapitalCoverage,omitempty"`
	AcidTest *float32 `json:"acidTest,omitempty"`
	CurrentRatio *float32 `json:"currentRatio,omitempty"`
}

// NewSearchCompanyDataTypeFinancialStability instantiates a new SearchCompanyDataTypeFinancialStability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCompanyDataTypeFinancialStability() *SearchCompanyDataTypeFinancialStability {
	this := SearchCompanyDataTypeFinancialStability{}
	return &this
}

// NewSearchCompanyDataTypeFinancialStabilityWithDefaults instantiates a new SearchCompanyDataTypeFinancialStability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCompanyDataTypeFinancialStabilityWithDefaults() *SearchCompanyDataTypeFinancialStability {
	this := SearchCompanyDataTypeFinancialStability{}
	return &this
}

// GetSecondaryMarginStructure returns the SecondaryMarginStructure field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeFinancialStability) GetSecondaryMarginStructure() float32 {
	if o == nil || IsNil(o.SecondaryMarginStructure) {
		var ret float32
		return ret
	}
	return *o.SecondaryMarginStructure
}

// GetSecondaryMarginStructureOk returns a tuple with the SecondaryMarginStructure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeFinancialStability) GetSecondaryMarginStructureOk() (*float32, bool) {
	if o == nil || IsNil(o.SecondaryMarginStructure) {
		return nil, false
	}
	return o.SecondaryMarginStructure, true
}

// HasSecondaryMarginStructure returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeFinancialStability) HasSecondaryMarginStructure() bool {
	if o != nil && !IsNil(o.SecondaryMarginStructure) {
		return true
	}

	return false
}

// SetSecondaryMarginStructure gets a reference to the given float32 and assigns it to the SecondaryMarginStructure field.
func (o *SearchCompanyDataTypeFinancialStability) SetSecondaryMarginStructure(v float32) {
	o.SecondaryMarginStructure = &v
}

// GetMarginStructure returns the MarginStructure field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeFinancialStability) GetMarginStructure() float32 {
	if o == nil || IsNil(o.MarginStructure) {
		var ret float32
		return ret
	}
	return *o.MarginStructure
}

// GetMarginStructureOk returns a tuple with the MarginStructure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeFinancialStability) GetMarginStructureOk() (*float32, bool) {
	if o == nil || IsNil(o.MarginStructure) {
		return nil, false
	}
	return o.MarginStructure, true
}

// HasMarginStructure returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeFinancialStability) HasMarginStructure() bool {
	if o != nil && !IsNil(o.MarginStructure) {
		return true
	}

	return false
}

// SetMarginStructure gets a reference to the given float32 and assigns it to the MarginStructure field.
func (o *SearchCompanyDataTypeFinancialStability) SetMarginStructure(v float32) {
	o.MarginStructure = &v
}

// GetFixedAssetsCoverageRate returns the FixedAssetsCoverageRate field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeFinancialStability) GetFixedAssetsCoverageRate() float32 {
	if o == nil || IsNil(o.FixedAssetsCoverageRate) {
		var ret float32
		return ret
	}
	return *o.FixedAssetsCoverageRate
}

// GetFixedAssetsCoverageRateOk returns a tuple with the FixedAssetsCoverageRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeFinancialStability) GetFixedAssetsCoverageRateOk() (*float32, bool) {
	if o == nil || IsNil(o.FixedAssetsCoverageRate) {
		return nil, false
	}
	return o.FixedAssetsCoverageRate, true
}

// HasFixedAssetsCoverageRate returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeFinancialStability) HasFixedAssetsCoverageRate() bool {
	if o != nil && !IsNil(o.FixedAssetsCoverageRate) {
		return true
	}

	return false
}

// SetFixedAssetsCoverageRate gets a reference to the given float32 and assigns it to the FixedAssetsCoverageRate field.
func (o *SearchCompanyDataTypeFinancialStability) SetFixedAssetsCoverageRate(v float32) {
	o.FixedAssetsCoverageRate = &v
}

// GetMarginStructureIndex returns the MarginStructureIndex field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeFinancialStability) GetMarginStructureIndex() float32 {
	if o == nil || IsNil(o.MarginStructureIndex) {
		var ret float32
		return ret
	}
	return *o.MarginStructureIndex
}

// GetMarginStructureIndexOk returns a tuple with the MarginStructureIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeFinancialStability) GetMarginStructureIndexOk() (*float32, bool) {
	if o == nil || IsNil(o.MarginStructureIndex) {
		return nil, false
	}
	return o.MarginStructureIndex, true
}

// HasMarginStructureIndex returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeFinancialStability) HasMarginStructureIndex() bool {
	if o != nil && !IsNil(o.MarginStructureIndex) {
		return true
	}

	return false
}

// SetMarginStructureIndex gets a reference to the given float32 and assigns it to the MarginStructureIndex field.
func (o *SearchCompanyDataTypeFinancialStability) SetMarginStructureIndex(v float32) {
	o.MarginStructureIndex = &v
}

// GetWorkingCapitalCoverage returns the WorkingCapitalCoverage field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeFinancialStability) GetWorkingCapitalCoverage() float32 {
	if o == nil || IsNil(o.WorkingCapitalCoverage) {
		var ret float32
		return ret
	}
	return *o.WorkingCapitalCoverage
}

// GetWorkingCapitalCoverageOk returns a tuple with the WorkingCapitalCoverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeFinancialStability) GetWorkingCapitalCoverageOk() (*float32, bool) {
	if o == nil || IsNil(o.WorkingCapitalCoverage) {
		return nil, false
	}
	return o.WorkingCapitalCoverage, true
}

// HasWorkingCapitalCoverage returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeFinancialStability) HasWorkingCapitalCoverage() bool {
	if o != nil && !IsNil(o.WorkingCapitalCoverage) {
		return true
	}

	return false
}

// SetWorkingCapitalCoverage gets a reference to the given float32 and assigns it to the WorkingCapitalCoverage field.
func (o *SearchCompanyDataTypeFinancialStability) SetWorkingCapitalCoverage(v float32) {
	o.WorkingCapitalCoverage = &v
}

// GetAcidTest returns the AcidTest field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeFinancialStability) GetAcidTest() float32 {
	if o == nil || IsNil(o.AcidTest) {
		var ret float32
		return ret
	}
	return *o.AcidTest
}

// GetAcidTestOk returns a tuple with the AcidTest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeFinancialStability) GetAcidTestOk() (*float32, bool) {
	if o == nil || IsNil(o.AcidTest) {
		return nil, false
	}
	return o.AcidTest, true
}

// HasAcidTest returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeFinancialStability) HasAcidTest() bool {
	if o != nil && !IsNil(o.AcidTest) {
		return true
	}

	return false
}

// SetAcidTest gets a reference to the given float32 and assigns it to the AcidTest field.
func (o *SearchCompanyDataTypeFinancialStability) SetAcidTest(v float32) {
	o.AcidTest = &v
}

// GetCurrentRatio returns the CurrentRatio field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeFinancialStability) GetCurrentRatio() float32 {
	if o == nil || IsNil(o.CurrentRatio) {
		var ret float32
		return ret
	}
	return *o.CurrentRatio
}

// GetCurrentRatioOk returns a tuple with the CurrentRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeFinancialStability) GetCurrentRatioOk() (*float32, bool) {
	if o == nil || IsNil(o.CurrentRatio) {
		return nil, false
	}
	return o.CurrentRatio, true
}

// HasCurrentRatio returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeFinancialStability) HasCurrentRatio() bool {
	if o != nil && !IsNil(o.CurrentRatio) {
		return true
	}

	return false
}

// SetCurrentRatio gets a reference to the given float32 and assigns it to the CurrentRatio field.
func (o *SearchCompanyDataTypeFinancialStability) SetCurrentRatio(v float32) {
	o.CurrentRatio = &v
}

func (o SearchCompanyDataTypeFinancialStability) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCompanyDataTypeFinancialStability) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SecondaryMarginStructure) {
		toSerialize["secondaryMarginStructure"] = o.SecondaryMarginStructure
	}
	if !IsNil(o.MarginStructure) {
		toSerialize["marginStructure"] = o.MarginStructure
	}
	if !IsNil(o.FixedAssetsCoverageRate) {
		toSerialize["fixedAssetsCoverageRate"] = o.FixedAssetsCoverageRate
	}
	if !IsNil(o.MarginStructureIndex) {
		toSerialize["marginStructureIndex"] = o.MarginStructureIndex
	}
	if !IsNil(o.WorkingCapitalCoverage) {
		toSerialize["workingCapitalCoverage"] = o.WorkingCapitalCoverage
	}
	if !IsNil(o.AcidTest) {
		toSerialize["acidTest"] = o.AcidTest
	}
	if !IsNil(o.CurrentRatio) {
		toSerialize["currentRatio"] = o.CurrentRatio
	}
	return toSerialize, nil
}

type NullableSearchCompanyDataTypeFinancialStability struct {
	value *SearchCompanyDataTypeFinancialStability
	isSet bool
}

func (v NullableSearchCompanyDataTypeFinancialStability) Get() *SearchCompanyDataTypeFinancialStability {
	return v.value
}

func (v *NullableSearchCompanyDataTypeFinancialStability) Set(val *SearchCompanyDataTypeFinancialStability) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCompanyDataTypeFinancialStability) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCompanyDataTypeFinancialStability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCompanyDataTypeFinancialStability(val *SearchCompanyDataTypeFinancialStability) *NullableSearchCompanyDataTypeFinancialStability {
	return &NullableSearchCompanyDataTypeFinancialStability{value: val, isSet: true}
}

func (v NullableSearchCompanyDataTypeFinancialStability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCompanyDataTypeFinancialStability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


