/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the CompanyMargoIdArrayType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyMargoIdArrayType{}

// CompanyMargoIdArrayType Array of Company MargoId
type CompanyMargoIdArrayType struct {
	MargoIds []string `json:"margoIds,omitempty"`
}

// NewCompanyMargoIdArrayType instantiates a new CompanyMargoIdArrayType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyMargoIdArrayType() *CompanyMargoIdArrayType {
	this := CompanyMargoIdArrayType{}
	return &this
}

// NewCompanyMargoIdArrayTypeWithDefaults instantiates a new CompanyMargoIdArrayType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyMargoIdArrayTypeWithDefaults() *CompanyMargoIdArrayType {
	this := CompanyMargoIdArrayType{}
	return &this
}

// GetMargoIds returns the MargoIds field value if set, zero value otherwise.
func (o *CompanyMargoIdArrayType) GetMargoIds() []string {
	if o == nil || IsNil(o.MargoIds) {
		var ret []string
		return ret
	}
	return o.MargoIds
}

// GetMargoIdsOk returns a tuple with the MargoIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyMargoIdArrayType) GetMargoIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.MargoIds) {
		return nil, false
	}
	return o.MargoIds, true
}

// HasMargoIds returns a boolean if a field has been set.
func (o *CompanyMargoIdArrayType) HasMargoIds() bool {
	if o != nil && !IsNil(o.MargoIds) {
		return true
	}

	return false
}

// SetMargoIds gets a reference to the given []string and assigns it to the MargoIds field.
func (o *CompanyMargoIdArrayType) SetMargoIds(v []string) {
	o.MargoIds = v
}

func (o CompanyMargoIdArrayType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyMargoIdArrayType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MargoIds) {
		toSerialize["margoIds"] = o.MargoIds
	}
	return toSerialize, nil
}

type NullableCompanyMargoIdArrayType struct {
	value *CompanyMargoIdArrayType
	isSet bool
}

func (v NullableCompanyMargoIdArrayType) Get() *CompanyMargoIdArrayType {
	return v.value
}

func (v *NullableCompanyMargoIdArrayType) Set(val *CompanyMargoIdArrayType) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyMargoIdArrayType) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyMargoIdArrayType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyMargoIdArrayType(val *CompanyMargoIdArrayType) *NullableCompanyMargoIdArrayType {
	return &NullableCompanyMargoIdArrayType{value: val, isSet: true}
}

func (v NullableCompanyMargoIdArrayType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyMargoIdArrayType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


