/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchCompanyDataTypeStructureRatios type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCompanyDataTypeStructureRatios{}

// SearchCompanyDataTypeStructureRatios struct for SearchCompanyDataTypeStructureRatios
type SearchCompanyDataTypeStructureRatios struct {
	NetFinancialDebtEquityNetWorth *float32 `json:"netFinancialDebtEquityNetWorth,omitempty"`
	PfnNetWorth *float32 `json:"pfnNetWorth,omitempty"`
	FinancialDebtComposition *float32 `json:"financialDebtComposition,omitempty"`
	NetDebtTotalSources *float32 `json:"netDebtTotalSources,omitempty"`
	GrossFinancialDebtNetWorth *float32 `json:"grossFinancialDebtNetWorth,omitempty"`
}

// NewSearchCompanyDataTypeStructureRatios instantiates a new SearchCompanyDataTypeStructureRatios object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCompanyDataTypeStructureRatios() *SearchCompanyDataTypeStructureRatios {
	this := SearchCompanyDataTypeStructureRatios{}
	return &this
}

// NewSearchCompanyDataTypeStructureRatiosWithDefaults instantiates a new SearchCompanyDataTypeStructureRatios object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCompanyDataTypeStructureRatiosWithDefaults() *SearchCompanyDataTypeStructureRatios {
	this := SearchCompanyDataTypeStructureRatios{}
	return &this
}

// GetNetFinancialDebtEquityNetWorth returns the NetFinancialDebtEquityNetWorth field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeStructureRatios) GetNetFinancialDebtEquityNetWorth() float32 {
	if o == nil || IsNil(o.NetFinancialDebtEquityNetWorth) {
		var ret float32
		return ret
	}
	return *o.NetFinancialDebtEquityNetWorth
}

// GetNetFinancialDebtEquityNetWorthOk returns a tuple with the NetFinancialDebtEquityNetWorth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeStructureRatios) GetNetFinancialDebtEquityNetWorthOk() (*float32, bool) {
	if o == nil || IsNil(o.NetFinancialDebtEquityNetWorth) {
		return nil, false
	}
	return o.NetFinancialDebtEquityNetWorth, true
}

// HasNetFinancialDebtEquityNetWorth returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeStructureRatios) HasNetFinancialDebtEquityNetWorth() bool {
	if o != nil && !IsNil(o.NetFinancialDebtEquityNetWorth) {
		return true
	}

	return false
}

// SetNetFinancialDebtEquityNetWorth gets a reference to the given float32 and assigns it to the NetFinancialDebtEquityNetWorth field.
func (o *SearchCompanyDataTypeStructureRatios) SetNetFinancialDebtEquityNetWorth(v float32) {
	o.NetFinancialDebtEquityNetWorth = &v
}

// GetPfnNetWorth returns the PfnNetWorth field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeStructureRatios) GetPfnNetWorth() float32 {
	if o == nil || IsNil(o.PfnNetWorth) {
		var ret float32
		return ret
	}
	return *o.PfnNetWorth
}

// GetPfnNetWorthOk returns a tuple with the PfnNetWorth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeStructureRatios) GetPfnNetWorthOk() (*float32, bool) {
	if o == nil || IsNil(o.PfnNetWorth) {
		return nil, false
	}
	return o.PfnNetWorth, true
}

// HasPfnNetWorth returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeStructureRatios) HasPfnNetWorth() bool {
	if o != nil && !IsNil(o.PfnNetWorth) {
		return true
	}

	return false
}

// SetPfnNetWorth gets a reference to the given float32 and assigns it to the PfnNetWorth field.
func (o *SearchCompanyDataTypeStructureRatios) SetPfnNetWorth(v float32) {
	o.PfnNetWorth = &v
}

// GetFinancialDebtComposition returns the FinancialDebtComposition field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeStructureRatios) GetFinancialDebtComposition() float32 {
	if o == nil || IsNil(o.FinancialDebtComposition) {
		var ret float32
		return ret
	}
	return *o.FinancialDebtComposition
}

// GetFinancialDebtCompositionOk returns a tuple with the FinancialDebtComposition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeStructureRatios) GetFinancialDebtCompositionOk() (*float32, bool) {
	if o == nil || IsNil(o.FinancialDebtComposition) {
		return nil, false
	}
	return o.FinancialDebtComposition, true
}

// HasFinancialDebtComposition returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeStructureRatios) HasFinancialDebtComposition() bool {
	if o != nil && !IsNil(o.FinancialDebtComposition) {
		return true
	}

	return false
}

// SetFinancialDebtComposition gets a reference to the given float32 and assigns it to the FinancialDebtComposition field.
func (o *SearchCompanyDataTypeStructureRatios) SetFinancialDebtComposition(v float32) {
	o.FinancialDebtComposition = &v
}

// GetNetDebtTotalSources returns the NetDebtTotalSources field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeStructureRatios) GetNetDebtTotalSources() float32 {
	if o == nil || IsNil(o.NetDebtTotalSources) {
		var ret float32
		return ret
	}
	return *o.NetDebtTotalSources
}

// GetNetDebtTotalSourcesOk returns a tuple with the NetDebtTotalSources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeStructureRatios) GetNetDebtTotalSourcesOk() (*float32, bool) {
	if o == nil || IsNil(o.NetDebtTotalSources) {
		return nil, false
	}
	return o.NetDebtTotalSources, true
}

// HasNetDebtTotalSources returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeStructureRatios) HasNetDebtTotalSources() bool {
	if o != nil && !IsNil(o.NetDebtTotalSources) {
		return true
	}

	return false
}

// SetNetDebtTotalSources gets a reference to the given float32 and assigns it to the NetDebtTotalSources field.
func (o *SearchCompanyDataTypeStructureRatios) SetNetDebtTotalSources(v float32) {
	o.NetDebtTotalSources = &v
}

// GetGrossFinancialDebtNetWorth returns the GrossFinancialDebtNetWorth field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeStructureRatios) GetGrossFinancialDebtNetWorth() float32 {
	if o == nil || IsNil(o.GrossFinancialDebtNetWorth) {
		var ret float32
		return ret
	}
	return *o.GrossFinancialDebtNetWorth
}

// GetGrossFinancialDebtNetWorthOk returns a tuple with the GrossFinancialDebtNetWorth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeStructureRatios) GetGrossFinancialDebtNetWorthOk() (*float32, bool) {
	if o == nil || IsNil(o.GrossFinancialDebtNetWorth) {
		return nil, false
	}
	return o.GrossFinancialDebtNetWorth, true
}

// HasGrossFinancialDebtNetWorth returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeStructureRatios) HasGrossFinancialDebtNetWorth() bool {
	if o != nil && !IsNil(o.GrossFinancialDebtNetWorth) {
		return true
	}

	return false
}

// SetGrossFinancialDebtNetWorth gets a reference to the given float32 and assigns it to the GrossFinancialDebtNetWorth field.
func (o *SearchCompanyDataTypeStructureRatios) SetGrossFinancialDebtNetWorth(v float32) {
	o.GrossFinancialDebtNetWorth = &v
}

func (o SearchCompanyDataTypeStructureRatios) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCompanyDataTypeStructureRatios) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetFinancialDebtEquityNetWorth) {
		toSerialize["netFinancialDebtEquityNetWorth"] = o.NetFinancialDebtEquityNetWorth
	}
	if !IsNil(o.PfnNetWorth) {
		toSerialize["pfnNetWorth"] = o.PfnNetWorth
	}
	if !IsNil(o.FinancialDebtComposition) {
		toSerialize["financialDebtComposition"] = o.FinancialDebtComposition
	}
	if !IsNil(o.NetDebtTotalSources) {
		toSerialize["netDebtTotalSources"] = o.NetDebtTotalSources
	}
	if !IsNil(o.GrossFinancialDebtNetWorth) {
		toSerialize["grossFinancialDebtNetWorth"] = o.GrossFinancialDebtNetWorth
	}
	return toSerialize, nil
}

type NullableSearchCompanyDataTypeStructureRatios struct {
	value *SearchCompanyDataTypeStructureRatios
	isSet bool
}

func (v NullableSearchCompanyDataTypeStructureRatios) Get() *SearchCompanyDataTypeStructureRatios {
	return v.value
}

func (v *NullableSearchCompanyDataTypeStructureRatios) Set(val *SearchCompanyDataTypeStructureRatios) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCompanyDataTypeStructureRatios) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCompanyDataTypeStructureRatios) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCompanyDataTypeStructureRatios(val *SearchCompanyDataTypeStructureRatios) *NullableSearchCompanyDataTypeStructureRatios {
	return &NullableSearchCompanyDataTypeStructureRatios{value: val, isSet: true}
}

func (v NullableSearchCompanyDataTypeStructureRatios) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCompanyDataTypeStructureRatios) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


