/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the CustomVariablesFiltersTypeNumericfiltersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomVariablesFiltersTypeNumericfiltersInner{}

// CustomVariablesFiltersTypeNumericfiltersInner struct for CustomVariablesFiltersTypeNumericfiltersInner
type CustomVariablesFiltersTypeNumericfiltersInner struct {
	VariableIndex *int32 `json:"variableIndex,omitempty"`
	Value *NumericFilterType `json:"value,omitempty"`
}

// NewCustomVariablesFiltersTypeNumericfiltersInner instantiates a new CustomVariablesFiltersTypeNumericfiltersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomVariablesFiltersTypeNumericfiltersInner() *CustomVariablesFiltersTypeNumericfiltersInner {
	this := CustomVariablesFiltersTypeNumericfiltersInner{}
	return &this
}

// NewCustomVariablesFiltersTypeNumericfiltersInnerWithDefaults instantiates a new CustomVariablesFiltersTypeNumericfiltersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomVariablesFiltersTypeNumericfiltersInnerWithDefaults() *CustomVariablesFiltersTypeNumericfiltersInner {
	this := CustomVariablesFiltersTypeNumericfiltersInner{}
	return &this
}

// GetVariableIndex returns the VariableIndex field value if set, zero value otherwise.
func (o *CustomVariablesFiltersTypeNumericfiltersInner) GetVariableIndex() int32 {
	if o == nil || IsNil(o.VariableIndex) {
		var ret int32
		return ret
	}
	return *o.VariableIndex
}

// GetVariableIndexOk returns a tuple with the VariableIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomVariablesFiltersTypeNumericfiltersInner) GetVariableIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.VariableIndex) {
		return nil, false
	}
	return o.VariableIndex, true
}

// HasVariableIndex returns a boolean if a field has been set.
func (o *CustomVariablesFiltersTypeNumericfiltersInner) HasVariableIndex() bool {
	if o != nil && !IsNil(o.VariableIndex) {
		return true
	}

	return false
}

// SetVariableIndex gets a reference to the given int32 and assigns it to the VariableIndex field.
func (o *CustomVariablesFiltersTypeNumericfiltersInner) SetVariableIndex(v int32) {
	o.VariableIndex = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CustomVariablesFiltersTypeNumericfiltersInner) GetValue() NumericFilterType {
	if o == nil || IsNil(o.Value) {
		var ret NumericFilterType
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomVariablesFiltersTypeNumericfiltersInner) GetValueOk() (*NumericFilterType, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CustomVariablesFiltersTypeNumericfiltersInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given NumericFilterType and assigns it to the Value field.
func (o *CustomVariablesFiltersTypeNumericfiltersInner) SetValue(v NumericFilterType) {
	o.Value = &v
}

func (o CustomVariablesFiltersTypeNumericfiltersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomVariablesFiltersTypeNumericfiltersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VariableIndex) {
		toSerialize["variableIndex"] = o.VariableIndex
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableCustomVariablesFiltersTypeNumericfiltersInner struct {
	value *CustomVariablesFiltersTypeNumericfiltersInner
	isSet bool
}

func (v NullableCustomVariablesFiltersTypeNumericfiltersInner) Get() *CustomVariablesFiltersTypeNumericfiltersInner {
	return v.value
}

func (v *NullableCustomVariablesFiltersTypeNumericfiltersInner) Set(val *CustomVariablesFiltersTypeNumericfiltersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomVariablesFiltersTypeNumericfiltersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomVariablesFiltersTypeNumericfiltersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomVariablesFiltersTypeNumericfiltersInner(val *CustomVariablesFiltersTypeNumericfiltersInner) *NullableCustomVariablesFiltersTypeNumericfiltersInner {
	return &NullableCustomVariablesFiltersTypeNumericfiltersInner{value: val, isSet: true}
}

func (v NullableCustomVariablesFiltersTypeNumericfiltersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomVariablesFiltersTypeNumericfiltersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


