/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchCompanyDataTypeEcofinTurnoverRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCompanyDataTypeEcofinTurnoverRange{}

// SearchCompanyDataTypeEcofinTurnoverRange struct for SearchCompanyDataTypeEcofinTurnoverRange
type SearchCompanyDataTypeEcofinTurnoverRange struct {
	Code *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewSearchCompanyDataTypeEcofinTurnoverRange instantiates a new SearchCompanyDataTypeEcofinTurnoverRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCompanyDataTypeEcofinTurnoverRange() *SearchCompanyDataTypeEcofinTurnoverRange {
	this := SearchCompanyDataTypeEcofinTurnoverRange{}
	return &this
}

// NewSearchCompanyDataTypeEcofinTurnoverRangeWithDefaults instantiates a new SearchCompanyDataTypeEcofinTurnoverRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCompanyDataTypeEcofinTurnoverRangeWithDefaults() *SearchCompanyDataTypeEcofinTurnoverRange {
	this := SearchCompanyDataTypeEcofinTurnoverRange{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeEcofinTurnoverRange) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeEcofinTurnoverRange) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeEcofinTurnoverRange) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *SearchCompanyDataTypeEcofinTurnoverRange) SetCode(v string) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeEcofinTurnoverRange) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeEcofinTurnoverRange) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeEcofinTurnoverRange) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SearchCompanyDataTypeEcofinTurnoverRange) SetDescription(v string) {
	o.Description = &v
}

func (o SearchCompanyDataTypeEcofinTurnoverRange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCompanyDataTypeEcofinTurnoverRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableSearchCompanyDataTypeEcofinTurnoverRange struct {
	value *SearchCompanyDataTypeEcofinTurnoverRange
	isSet bool
}

func (v NullableSearchCompanyDataTypeEcofinTurnoverRange) Get() *SearchCompanyDataTypeEcofinTurnoverRange {
	return v.value
}

func (v *NullableSearchCompanyDataTypeEcofinTurnoverRange) Set(val *SearchCompanyDataTypeEcofinTurnoverRange) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCompanyDataTypeEcofinTurnoverRange) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCompanyDataTypeEcofinTurnoverRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCompanyDataTypeEcofinTurnoverRange(val *SearchCompanyDataTypeEcofinTurnoverRange) *NullableSearchCompanyDataTypeEcofinTurnoverRange {
	return &NullableSearchCompanyDataTypeEcofinTurnoverRange{value: val, isSet: true}
}

func (v NullableSearchCompanyDataTypeEcofinTurnoverRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCompanyDataTypeEcofinTurnoverRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


