/*
Global Marketing Solution

## Overview

API version: 1.0.0
Contact: PM_Margo@crif.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crifmargo

import (
	"encoding/json"
)

// checks if the SearchCompanyDataTypeFinancialStatementKpi type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCompanyDataTypeFinancialStatementKpi{}

// SearchCompanyDataTypeFinancialStatementKpi struct for SearchCompanyDataTypeFinancialStatementKpi
type SearchCompanyDataTypeFinancialStatementKpi struct {
	DebtsTurnover *float32 `json:"debtsTurnover,omitempty"`
	TotalInventoryTurnover *float32 `json:"totalInventoryTurnover,omitempty"`
}

// NewSearchCompanyDataTypeFinancialStatementKpi instantiates a new SearchCompanyDataTypeFinancialStatementKpi object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCompanyDataTypeFinancialStatementKpi() *SearchCompanyDataTypeFinancialStatementKpi {
	this := SearchCompanyDataTypeFinancialStatementKpi{}
	return &this
}

// NewSearchCompanyDataTypeFinancialStatementKpiWithDefaults instantiates a new SearchCompanyDataTypeFinancialStatementKpi object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCompanyDataTypeFinancialStatementKpiWithDefaults() *SearchCompanyDataTypeFinancialStatementKpi {
	this := SearchCompanyDataTypeFinancialStatementKpi{}
	return &this
}

// GetDebtsTurnover returns the DebtsTurnover field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeFinancialStatementKpi) GetDebtsTurnover() float32 {
	if o == nil || IsNil(o.DebtsTurnover) {
		var ret float32
		return ret
	}
	return *o.DebtsTurnover
}

// GetDebtsTurnoverOk returns a tuple with the DebtsTurnover field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeFinancialStatementKpi) GetDebtsTurnoverOk() (*float32, bool) {
	if o == nil || IsNil(o.DebtsTurnover) {
		return nil, false
	}
	return o.DebtsTurnover, true
}

// HasDebtsTurnover returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeFinancialStatementKpi) HasDebtsTurnover() bool {
	if o != nil && !IsNil(o.DebtsTurnover) {
		return true
	}

	return false
}

// SetDebtsTurnover gets a reference to the given float32 and assigns it to the DebtsTurnover field.
func (o *SearchCompanyDataTypeFinancialStatementKpi) SetDebtsTurnover(v float32) {
	o.DebtsTurnover = &v
}

// GetTotalInventoryTurnover returns the TotalInventoryTurnover field value if set, zero value otherwise.
func (o *SearchCompanyDataTypeFinancialStatementKpi) GetTotalInventoryTurnover() float32 {
	if o == nil || IsNil(o.TotalInventoryTurnover) {
		var ret float32
		return ret
	}
	return *o.TotalInventoryTurnover
}

// GetTotalInventoryTurnoverOk returns a tuple with the TotalInventoryTurnover field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCompanyDataTypeFinancialStatementKpi) GetTotalInventoryTurnoverOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalInventoryTurnover) {
		return nil, false
	}
	return o.TotalInventoryTurnover, true
}

// HasTotalInventoryTurnover returns a boolean if a field has been set.
func (o *SearchCompanyDataTypeFinancialStatementKpi) HasTotalInventoryTurnover() bool {
	if o != nil && !IsNil(o.TotalInventoryTurnover) {
		return true
	}

	return false
}

// SetTotalInventoryTurnover gets a reference to the given float32 and assigns it to the TotalInventoryTurnover field.
func (o *SearchCompanyDataTypeFinancialStatementKpi) SetTotalInventoryTurnover(v float32) {
	o.TotalInventoryTurnover = &v
}

func (o SearchCompanyDataTypeFinancialStatementKpi) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCompanyDataTypeFinancialStatementKpi) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DebtsTurnover) {
		toSerialize["debtsTurnover"] = o.DebtsTurnover
	}
	if !IsNil(o.TotalInventoryTurnover) {
		toSerialize["totalInventoryTurnover"] = o.TotalInventoryTurnover
	}
	return toSerialize, nil
}

type NullableSearchCompanyDataTypeFinancialStatementKpi struct {
	value *SearchCompanyDataTypeFinancialStatementKpi
	isSet bool
}

func (v NullableSearchCompanyDataTypeFinancialStatementKpi) Get() *SearchCompanyDataTypeFinancialStatementKpi {
	return v.value
}

func (v *NullableSearchCompanyDataTypeFinancialStatementKpi) Set(val *SearchCompanyDataTypeFinancialStatementKpi) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCompanyDataTypeFinancialStatementKpi) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCompanyDataTypeFinancialStatementKpi) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCompanyDataTypeFinancialStatementKpi(val *SearchCompanyDataTypeFinancialStatementKpi) *NullableSearchCompanyDataTypeFinancialStatementKpi {
	return &NullableSearchCompanyDataTypeFinancialStatementKpi{value: val, isSet: true}
}

func (v NullableSearchCompanyDataTypeFinancialStatementKpi) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCompanyDataTypeFinancialStatementKpi) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


